# Generated by Django 5.0.3 on 2024-11-06 22:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_dexquotepair_ingest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtCeiling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('data', models.JSONField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chain')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['chain', 'controller', 'timestamp'], name='debt_ceiling_cmt_idx')],
            },
        ),
    ]
