# Generated by Django 5.0.3 on 2024-11-07 02:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dexquotepair_ingest'),
        ('curve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.TextField()),
                ('block_number', models.IntegerField()),
                ('amm', models.TextField()),
                ('monetary_policy', models.TextField()),
                ('A', models.TextField()),
                ('amm_price', models.TextField()),
                ('oracle_price', models.TextField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chain')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['chain', 'controller', 'created_at'], name='controller_cmt_idx')],
            },
        ),
    ]
