# Generated by Django 5.0.3 on 2024-11-21 11:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dexquotepair_ingest'),
        ('curve', '0004_curvemarketsnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurveLlammaTrades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.TextField()),
                ('day', models.DateField()),
                ('sold', models.TextField()),
                ('bought', models.TextField()),
                ('fee', models.TextField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
