# Generated by Django 5.0.3 on 2024-11-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dexquotepair_ingest'),
        ('curve', '0005_curvellammatrades'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='curvellammatrades',
            constraint=models.UniqueConstraint(fields=('chain', 'controller', 'day'), name='llamma_trades_asset_chain_day_idx'),
        ),
    ]
