# Generated by Django 5.0.3 on 2024-11-21 16:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dexquotepair_ingest'),
        ('curve', '0006_curvellammatrades_llamma_trades_asset_chain_day_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurveLlammaEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.TextField()),
                ('day', models.DateField()),
                ('deposit', models.TextField()),
                ('withdrawal', models.TextField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='curvellammaevents',
            constraint=models.UniqueConstraint(fields=('chain', 'controller', 'day'), name='llamma_events_asset_chain_day_idx'),
        ),
    ]
