# Generated by Django 5.0.3 on 2024-11-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curve', '0007_curvellammaevents_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curvellammatrades',
            old_name='fee',
            new_name='fee_x',
        ),
        migrations.AddField(
            model_name='curvellammatrades',
            name='fee_y',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
