# Generated by Django 5.0.3 on 2024-11-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curve', '0010_curvemarkets'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtceiling',
            name='top5_debt',
            field=models.TextField(default='0'),
        ),
    ]
