# Generated by Django 5.0.3 on 2024-11-23 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dexquotepair_ingest'),
        ('curve', '0011_debtceiling_top5_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurveMarketLosses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.TextField()),
                ('timestamp', models.DateTimeField(null=True)),
                ('data', models.JSONField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurveMarketSoftLiquidations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.TextField()),
                ('timestamp', models.DateTimeField(null=True)),
                ('data', models.JSONField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='curvemarketlosses',
            constraint=models.UniqueConstraint(fields=('chain', 'controller', 'timestamp'), name='losses_asset_chain_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='curvemarketsoftliquidations',
            constraint=models.UniqueConstraint(fields=('chain', 'controller', 'timestamp'), name='soft_liquidation_asset_chain_ts_idx'),
        ),
    ]
