# Generated by Django 5.0.3 on 2024-11-29 08:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dexquotepair_ingest'),
        ('curve', '0012_curvemarketlosses_curvemarketsoftliquidations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurveScores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.TextField()),
                ('relative_cr_score', models.TextField()),
                ('absolute_cr_score', models.TextField()),
                ('aggregate_cr_score', models.TextField()),
                ('bad_debt_score', models.TextField()),
                ('aggregate_prob_drop_score', models.TextField()),
                ('collateral_under_sl_score', models.TextField()),
                ('relative_collateral_under_sl_score', models.TextField()),
                ('aggregate_collateral_under_sl_score', models.TextField()),
                ('vol_ratio_score', models.TextField()),
                ('beta_score', models.TextField()),
                ('aggregate_vol_ratio_score', models.TextField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
