# Generated by Django 5.0.3 on 2024-11-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curve', '0013_curvescores'),
    ]

    operations = [
        migrations.AddField(
            model_name='curvescores',
            name='prob_drop1_score',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curvescores',
            name='prob_drop2_score',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
