# Generated by Django 5.0.3 on 2024-12-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curve', '0016_rename_debtceiling_top5debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curvescores',
            name='aggregate_borrower_distribution_score',
            field=models.TextField(default='0'),
        ),
    ]
