# Generated by Django 5.0.3 on 2024-12-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curve', '0018_simuliq'),
    ]

    operations = [
        migrations.AddField(
            model_name='curvescores',
            name='sl_responsiveness_score',
            field=models.TextField(default='0'),
        ),
    ]
