# Generated by Django 5.0.3 on 2024-12-25 00:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_erc20_is_denomination_asset_erc20_is_gov_asset_and_more'),
        ('curve', '0019_curvescores_sl_responsiveness_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurveScoresDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.TextField()),
                ('cr_ratio', models.TextField(default='0')),
                ('cr_ratio_7d', models.TextField(default='0')),
                ('cr_ratio_30d', models.TextField(default='0')),
                ('cr_7d_30d_ratio', models.TextField(default='0')),
                ('hhi', models.TextField(default='0')),
                ('hhi_ideal', models.TextField(default='0')),
                ('hhi_ratio', models.TextField(default='0')),
                ('hhi_7d', models.TextField(default='0')),
                ('hhi_30d', models.TextField(default='0')),
                ('hhi_7d_30d_ratio', models.TextField(default='0')),
                ('prob_drop1', models.TextField(default='0')),
                ('prob_drop2', models.TextField(default='0')),
                ('debt_under_sl_ratio', models.TextField(default='0')),
                ('debt_under_sl_ratio_7d', models.TextField(default='0')),
                ('debt_under_sl_ratio_30d', models.TextField(default='0')),
                ('collateral_under_sl_ratio', models.TextField(default='0')),
                ('collateral_under_sl_ratio_7d', models.TextField(default='0')),
                ('collateral_under_sl_ratio_30d', models.TextField(default='0')),
                ('volatility_45d', models.TextField(default='0')),
                ('volatility_180d', models.TextField(default='0')),
                ('volatility_ratio', models.TextField(default='0')),
                ('beta', models.TextField(default='0')),
                ('total_debt', models.TextField(default='0')),
                ('borrowable', models.TextField(default='0')),
                ('bad_debt', models.TextField(default='0')),
                ('recommended_debt_ceiling', models.TextField(default='0')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
