# Generated by Django 5.0.3 on 2024-12-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curve', '0020_aaveuserdata'),
        ('curve', '0020_create_curve_scores_detail'),
    ]

    operations = [
    ]
