# Generated by Django 5.0.3 on 2024-12-26 05:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_erc20_is_denomination_asset_erc20_is_gov_asset_and_more'),
        ('curve', '0021_merge_20241225_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top5debt',
            name='data',
        ),
        migrations.CreateModel(
            name='CurveUserData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.TextField()),
                ('data', models.JSONField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
