# Generated by Django 5.0.3 on 2024-12-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curve', '0023_rename_total_supply_curvemetrics_circulating_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='curvescores',
            name='interdependency_price_momentum_score',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='curvescores',
            name='interdependency_volatility_score',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='curvescores',
            name='weighted_average_score',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='curvescoresdetail',
            name='max_ltv',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='curvescoresdetail',
            name='min_ltv',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='curvescoresdetail',
            name='sl_peak_analysis_score',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='curvescoresdetail',
            name='sl_spread_analysis_score',
            field=models.TextField(default='0'),
        ),
    ]
