version: '3.4'

services:
  web:
    # env_file: env/local/app.env
    environment:
      PORT: 8000
      MEDIA_DIR: 'media'
      REDIS_URL: 'redis://localhost:6379/0'
      ENVIRONMENT: 'local'

      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PORT: 5432
      POSTGRES_HOST: 'postgres'

      MONGODB_CONNECTION_STRING: 'mongodb://mongo:27017/'

      TIMEOUT: 9
    build:
      context: .
      dockerfile: Dockerfiles/app_worker.Dockerfile
    ports:
      - '8000:8000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - .:/code
      - media:/code/media

  # redis:
    # image: redis:latest
    # ports:
      # - "6379:6379"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
          - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: test
      # MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  media:
  mongodata:
