version: '3.4'

services:
  web:
    # env_file: env/local/app.env
    environment:
      TIMEOUT: 9
      PORT: 8000
      REDIS_URL: redis://redis:6379/0
    build:
      context: .
      dockerfile: Dockerfiles/app_worker.Dockerfile
    ports:
      - '8000:8000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
          - media:/code/media
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
          - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  media: