# Generated by Django 5.0.3 on 2024-04-07 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_cryologsmetadata_extracted"),
        ("uniswap", "0003_remove_paircreated_transaction_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
