# Generated by Django 5.0.3 on 2024-05-20 11:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERC20',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=59, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('decimals', models.IntegerField(default=0)),
                ('contract_address', models.CharField(max_length=50)),
                ('pricing_metadata', models.JSONField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chain')),
            ],
            options={
                'unique_together': {('chain', 'contract_address')},
            },
        ),
        migrations.CreateModel(
            name='UniswapLPPosition',
            fields=[
                ('erc20_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.erc20')),
                ('tickLower', models.CharField(max_length=50)),
                ('tickUpper', models.CharField(max_length=50)),
                ('liquidity', models.CharField(max_length=50)),
                ('token0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erc_token0', to='core.erc20')),
                ('token1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erc_token1', to='core.erc20')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.erc20',),
        ),
    ]
