# Generated by Django 5.0.3 on 2024-05-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_uniswaplpposition_liquidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erc20',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='erc20',
            name='pricing_metadata',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='erc20',
            name='symbol',
            field=models.CharField(blank=True, max_length=59, null=True),
        ),
    ]
