# Generated by Django 5.0.3 on 2024-07-27 11:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_erc20_erc20_unique_token_contract_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='DexQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.IntegerField()),
                ('dex_aggregator', models.CharField(max_length=50)),
                ('src', models.CharField(max_length=42)),
                ('src_decimals', models.IntegerField()),
                ('dst', models.CharField(max_length=42)),
                ('dest_decimals', models.IntegerField()),
                ('in_amount_usd', models.FloatField()),
                ('in_amount', models.TextField()),
                ('out_amount', models.TextField()),
                ('market_price', models.FloatField()),
                ('price', models.FloatField()),
                ('price_impact', models.FloatField()),
                ('timestamp', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
