# Generated by Django 5.0.3 on 2024-09-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dexquote'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dexquote',
            index=models.Index(fields=['src', 'dst'], name='src_dst_idx'),
        ),
        migrations.AddIndex(
            model_name='dexquote',
            index=models.Index(fields=['src'], name='src_idx'),
        ),
        migrations.AddIndex(
            model_name='dexquote',
            index=models.Index(fields=['dst'], name='dst_idx'),
        ),
    ]
