# Generated by Django 5.0.3 on 2024-09-26 16:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dexquote_src_dst_idx_dexquote_src_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DexQuotePair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('dst_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_asset_pairs', to='core.erc20')),
                ('src_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_asset_pairs', to='core.erc20')),
            ],
            options={
                'unique_together': {('src_asset', 'dst_asset')},
            },
        ),
        migrations.AddField(
            model_name='dexquote',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dexquotepair'),
        ),
    ]
