# Generated by Django 5.0.3 on 2024-11-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dexquotepair_ingest'),
    ]

    operations = [
        migrations.AddField(
            model_name='erc20',
            name='is_denomination_asset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='erc20',
            name='is_gov_asset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='erc20',
            name='is_lp_asset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='erc20',
            name='is_stablecoin_asset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='erc20',
            name='is_staked_asset',
            field=models.BooleanField(default=False),
        ),
    ]
