# Generated by Django 5.0.3 on 2024-05-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_uniswaplpposition_token0_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='erc20',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='erc20',
            constraint=models.UniqueConstraint(fields=('contract_address', 'chain'), name='erc20_unique_token_contract_chain'),
        ),
    ]
