# Generated by Django 5.0.3 on 2024-05-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_erc20_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uniswaplpposition',
            name='unique_token_contract_chain',
        ),
    ]
