# Generated by Django 5.0.3 on 2024-05-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_uniswaplpposition_unique_token_contract_chain'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='uniswaplpposition',
            constraint=models.UniqueConstraint(fields=('token_id', 'erc20__contract_address', 'erc20__chain'), name='unique_token_contract_chain'),
        ),
    ]
