# Generated by Django 5.0.3 on 2024-05-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_uniswaplpposition_unique_token_contract_chain'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uniswaplpposition',
            name='unique_token_contract_chain',
        ),
    ]
