# Generated by Django 5.0.3 on 2024-04-07 13:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_cryologsmetadata_extracted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairCreated',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('token0', models.CharField(max_length=255, unique=True)),
                ('token1', models.CharField(max_length=255, unique=True)),
                ('pair', models.CharField(max_length=255, unique=True)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
