# Generated by Django 5.0.3 on 2024-08-17 21:07

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ethena", "0002_alter_reservefundmetrics_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReserveFundBreakdown",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("tokens", models.JSONField()),
                ("positions", models.JSONField()),
                ("tokens_usd_value", models.TextField()),
                ("positions_usd_value", models.TextField()),
                ("total_usd_value", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
