# Generated by Django 5.0.3 on 2024-08-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethena', '0006_curvepoolmetrics_curvepoolsnapshots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curvepoolmetrics',
            name='address',
        ),
        migrations.RemoveField(
            model_name='curvepoolsnapshots',
            name='address',
        ),
    ]
