# Generated by Django 5.0.3 on 2024-08-25 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ethena", "0007_remove_curvepoolmetrics_address_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UniswapStats",
            new_name="UniswapMetrics",
        ),
    ]
