# Generated by Django 5.0.3 on 2024-08-25 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ethena", "0008_rename_uniswapstats_uniswapmetrics"),
    ]

    operations = [
        migrations.RenameField(
            model_name="curvepoolmetrics",
            old_name="data",
            new_name="metrics",
        ),
        migrations.RenameField(
            model_name="curvepoolsnapshots",
            old_name="data",
            new_name="snapshots",
        ),
        migrations.RenameField(
            model_name="uniswapmetrics",
            old_name="data",
            new_name="metrics",
        ),
    ]
