# Generated by Django 5.0.3 on 2024-08-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ethena", "0010_chainmetrics_total_dai_staked_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="curvepoolsnapshots",
            old_name="snapshots",
            new_name="snapshot",
        ),
        migrations.AddField(
            model_name="curvepoolsnapshots",
            name="address",
            field=models.TextField(default=""),
        ),
    ]
