# Generated by Django 5.0.3 on 2024-09-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethena', '0011_rename_snapshots_curvepoolsnapshots_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainmetrics',
            name='dai_price',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='chainmetrics',
            name='usdt_price',
            field=models.TextField(default='0'),
        ),
    ]
