# Generated by Django 5.0.3 on 2024-09-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethena', '0012_chainmetrics_dai_price_chainmetrics_usdt_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniswapMetrics',
            new_name='UniswapPoolMetrics',
        ),
    ]
