# Generated by Django 5.0.3 on 2024-09-03 20:48

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ethena", "0013_rename_uniswapmetrics_uniswappoolmetrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniswapPoolSnapshots",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("timestamp", models.DateTimeField()),
                ("address", models.TextField()),
                ("snapshot", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="UniswapPoolMetrics",
        ),
        migrations.AlterField(
            model_name="curvepoolsnapshots",
            name="address",
            field=models.TextField(),
        ),
    ]
