# Generated by Django 5.0.3 on 2024-09-05 19:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dexquote'),
        ('ethena', '0014_uniswappoolsnapshots_delete_uniswappoolmetrics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurvePoolInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField()),
                ('address', models.TextField()),
                ('info', models.JSONField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CurvePoolMetrics',
        ),
    ]
