# Generated by Django 5.0.3 on 2024-09-15 18:54

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ethena", "0015_curvepoolinfo_delete_curvepoolmetrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="StakingMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("day", models.DateTimeField(unique=True)),
                ("usde_mint", models.TextField()),
                ("usde_burn", models.TextField()),
                ("supply_usde", models.TextField()),
                ("staked_usde", models.TextField()),
                ("unstake_usde", models.TextField()),
                ("unstake_susde", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
