# Generated by Django 5.0.3 on 2024-09-21 18:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethena', '0018_chainmetrics_total_buidl_issued_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitQueueMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('withdraw_day', models.DateTimeField()),
                ('unlock_day', models.DateTimeField(unique=True)),
                ('usde', models.TextField()),
                ('susde', models.TextField()),
                ('total_usde', models.TextField()),
                ('total_susde', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
