# Generated by Django 5.0.3 on 2024-09-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_dexquotepair_ingest"),
        ("ethena", "0019_exitqueuemetrics"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chainmetrics",
            index=models.Index(fields=["block_timestamp"], name="block_timestamp_idx"),
        ),
    ]
