# Generated by Django 5.0.3 on 2024-10-08 17:35

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ethena", "0020_chainmetrics_block_timestamp_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApyMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("timestamp", models.DateTimeField()),
                ("pool_id", models.TextField()),
                ("symbol", models.TextField()),
                ("tvl_usd", models.TextField()),
                ("apy", models.TextField()),
                ("apy_base", models.TextField()),
                ("apy_reward", models.TextField()),
                ("il7d", models.TextField()),
                ("apy_base_7d", models.TextField()),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["pool_id", "timestamp"], name="pool_id_timestamp_idx"
                    )
                ],
            },
        ),
    ]
