# Generated by Django 5.0.3 on 2024-10-09 02:29

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ethena", "0021_apymetrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingRateMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("timestamp", models.DateTimeField()),
                ("symbol", models.TextField()),
                ("exchange", models.TextField()),
                ("rate", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveIndex(
            model_name="apymetrics",
            name="pool_id_timestamp_idx",
        ),
        migrations.AddConstraint(
            model_name="apymetrics",
            constraint=models.UniqueConstraint(
                fields=("pool_id", "timestamp"), name="pool_id_timestamp_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fundingratemetrics",
            constraint=models.UniqueConstraint(
                fields=("timestamp", "symbol", "exchange"),
                name="timestamp_asset_cex_rate_idx",
            ),
        ),
    ]
