# Generated by Django 5.0.3 on 2024-10-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ethena", "0022_fundingratemetrics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apymetrics",
            name="apy",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="apymetrics",
            name="apy_base",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="apymetrics",
            name="apy_base_7d",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="apymetrics",
            name="apy_reward",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="apymetrics",
            name="il7d",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="apymetrics",
            name="tvl_usd",
            field=models.TextField(null=True),
        ),
    ]
