# Generated by Django 5.0.3 on 2024-10-13 21:59

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethena', '0024_buidlyieldmetrics_ustbyieldmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsdmMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(unique=True)),
                ('holders', models.JSONField()),
                ('index', models.TextField()),
                ('apy', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chainmetrics',
            name='buidl_wallet_count',
            field=models.TextField(default='0'),
        ),
    ]
