# Generated by Django 5.0.3 on 2024-10-13 22:41

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ethena", "0025_usdmmetrics_chainmetrics_buidl_wallet_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuidlRedemptionMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateTimeField(unique=True)),
                ("balance", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
