# Generated by Django 5.0.3 on 2024-09-05 08:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebtMetadataSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField()),
                ('timestamp', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
