# Generated by Django 5.0.3 on 2024-04-19 17:14

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0005_delete_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionFinished",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_hash",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("block_number", models.IntegerField()),
                ("timestamp", models.IntegerField(null=True)),
                ("transaction_index", models.IntegerField(null=True)),
                ("log_index", models.IntegerField(null=True)),
                ("pool_address", models.TextField()),
                ("account", models.TextField()),
                ("creditor", models.TextField()),
                ("start_debt", models.TextField()),
                ("initiation_reward", models.TextField()),
                ("termination_reward", models.TextField()),
                ("penalty", models.TextField()),
                ("bad_debt", models.TextField()),
                ("surplus", models.TextField()),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.chain"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuctionStarted",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_hash",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("block_number", models.IntegerField()),
                ("timestamp", models.IntegerField(null=True)),
                ("transaction_index", models.IntegerField(null=True)),
                ("log_index", models.IntegerField(null=True)),
                ("pool_address", models.TextField()),
                ("account", models.TextField()),
                ("creditor", models.TextField()),
                ("open_debt", models.TextField()),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.chain"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Borrow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_hash",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("block_number", models.IntegerField()),
                ("timestamp", models.IntegerField(null=True)),
                ("transaction_index", models.IntegerField(null=True)),
                ("log_index", models.IntegerField(null=True)),
                ("pool_address", models.TextField()),
                ("account", models.TextField()),
                ("by", models.TextField()),
                ("to", models.TextField()),
                ("amount", models.TextField()),
                ("fee", models.BigIntegerField()),
                ("referrer", models.TextField()),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.chain"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Repay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_hash",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("block_number", models.IntegerField()),
                ("timestamp", models.IntegerField(null=True)),
                ("transaction_index", models.IntegerField(null=True)),
                ("log_index", models.IntegerField(null=True)),
                ("pool_address", models.TextField()),
                ("account", models.TextField()),
                ("from_address", models.TextField()),
                ("amount", models.TextField()),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.chain"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
