# Generated by Django 5.0.3 on 2024-04-26 21:05

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arcadia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountAssets",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("account", models.TextField(unique=True)),
                ("usdc_value", models.TextField()),
                ("weth_value", models.TextField()),
                ("asset_details", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
