# Generated by Django 5.0.3 on 2024-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcadia', '0002_accountassets'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountassets',
            name='asset_details_usd',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountassets',
            name='collateral_value',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountassets',
            name='collateral_value_usd',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountassets',
            name='numeraire',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
