# Generated by Django 5.0.3 on 2024-04-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arcadia", "0003_accountassets_asset_details_usd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountassets",
            name="debt_usd",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
