# Generated by Django 5.0.3 on 2024-05-01 10:24

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arcadia", "0004_accountassets_debt_usd"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("weighted_cr", models.FloatField()),
                ("weighted_cr_usdc", models.FloatField()),
                ("weighted_cr_weth", models.FloatField()),
                ("active_auctions", models.IntegerField()),
                ("active_auctions_usd", models.IntegerField()),
                ("active_auctions_weth", models.IntegerField()),
                ("total_debt", models.TextField()),
                ("total_debt_usdc", models.TextField()),
                ("total_debt_weth", models.TextField()),
                ("total_collateral", models.TextField()),
                ("total_collateral_usdc", models.TextField()),
                ("total_collateral_weth", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
