# Generated by Django 5.0.3 on 2024-06-13 11:15

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arcadia", "0005_metricsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("sim_id", models.TextField(unique=True)),
                ("prices", models.JSONField()),
                ("timestamp", models.DateTimeField()),
                ("total_non_liquidated_accounts", models.IntegerField()),
                ("total_active_auctions", models.IntegerField()),
                ("total_fully_liquidated_accounts", models.IntegerField()),
                ("total_outstanding_debt", models.TextField()),
                ("bad_debt_per_asset", models.JSONField()),
                ("total_exposure_per_asset", models.JSONField()),
                ("total_insolvent_value", models.TextField()),
                ("total_protocol_revenue", models.TextField()),
                ("position_weighted_collateral_ratio", models.TextField()),
                ("protocol_revenue_per_asset", models.JSONField()),
                ("start_timestamp", models.IntegerField()),
                ("end_timestamp", models.IntegerField()),
                ("pool_address", models.TextField()),
                ("numeraire", models.TextField()),
                ("liquidation_factors", models.JSONField()),
            ],
            options={
                "db_table": "sim_snapshot",
                "indexes": [
                    models.Index(
                        fields=["sim_id"], name="sim_snapsho_sim_id_29790e_idx"
                    )
                ],
            },
        ),
    ]
