# Generated by Django 5.0.3 on 2024-06-13 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arcadia", "0006_simsnapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simsnapshot",
            name="timestamp",
        ),
    ]
