# Generated by Django 5.0.3 on 2024-06-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arcadia", "0007_remove_simsnapshot_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="simsnapshot",
            name="timestamp",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
