# Generated by Django 5.0.3 on 2024-06-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arcadia", "0008_simsnapshot_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="simsnapshot",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
