# Generated by Django 5.0.3 on 2024-06-21 11:16

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arcadia", "0009_simsnapshot_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="OracleSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("spot_prices", models.JSONField()),
                ("chainlink_prices", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
