# Generated by Django 5.0.3 on 2024-06-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arcadia", "0010_oraclesnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="oraclesnapshot",
            name="missed_assets",
            field=models.JSONField(null=True),
        ),
    ]
