# Generated by Django 5.0.3 on 2024-06-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arcadia", "0011_oraclesnapshot_missed_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricsnapshot",
            name="collateral_distribution",
            field=models.JSONField(null=True),
        ),
    ]
