# Generated by Django 5.0.3 on 2024-07-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arcadia", "0012_metricsnapshot_collateral_distribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountassets",
            name="liquidation_value",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="accountassets",
            name="used_margin",
            field=models.TextField(null=True),
        ),
    ]
