# Generated by Django 5.0.3 on 2024-07-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcadia', '0014_accountassets_healthy'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsnapshot',
            name='total_supply_usdc',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='total_supply_weth',
            field=models.BigIntegerField(null=True),
        ),
    ]
