# Generated by Django 5.0.3 on 2024-07-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcadia', '0015_metricsnapshot_total_supply_usdc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsnapshot',
            name='total_supply_usdc',
            field=models.DecimalField(decimal_places=5, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='metricsnapshot',
            name='total_supply_weth',
            field=models.DecimalField(decimal_places=5, max_digits=30, null=True),
        ),
    ]
