# Generated by Django 5.0.3 on 2024-07-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arcadia", "0017_metricsnapshot_total_liquidity_usdc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountassets",
            name="position_distribution",
            field=models.JSONField(null=True),
        ),
    ]
