# Generated by Django 5.0.3 on 2024-07-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcadia', '0018_accountassets_position_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountassets',
            name='position_distribution_usd',
            field=models.JSONField(null=True),
        ),
    ]
